Repository team-swith/swith-client, pull requests merged in 2024-08, with the labels that each got.

#6 디자인 토큰 정의 및 공통 컴포넌트 제작
  app/layout.tsx
  app/page.tsx
  package.json
  pnpm-lock.yaml
  public/fonts/PretendardVariable.woff2
  src/components/common/bottom-nav-bar.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/chip.tsx
  src/components/ui/select.tsx
  src/components/ui/tabs.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 퍼블리싱

#10 SVGR 라이브러리 설정
  next.config.mjs
  package.json
  pnpm-lock.yaml
Labels: ✨ 기능

#11 BottomNavBar에 아이콘 추가하기
  src/assets/icon_mypage.svg
  src/assets/icon_search.svg
  src/assets/icon_studyroom.svg
  src/components/common/bottom-nav-bar.tsx
Labels: 🛠 개선

#15 스터디 탐색 퍼블리싱
  app/search/page.tsx
  src/components/common/bottom-nav-bar.tsx
  src/components/ui/card.tsx
Labels: 🎨 퍼블리싱

#17 로그인/회원가입 퍼블리싱
  app/component-demo/page.tsx
  app/on-boarding/page.tsx
  app/page.tsx
  app/walk-through/page.tsx
  package.json
  pnpm-lock.yaml
  src/assets/main/bg_background.svg
  src/assets/main/bg_rocket.svg
  src/assets/main/login_google.svg
  src/assets/main/login_kakao.svg
  src/assets/main/login_naver.svg
  src/components/ui/chip.tsx
  src/components/ui/progress.tsx
Labels: 🎨 퍼블리싱

#19 팀원 탐색 페이지 퍼블리싱
  app/search/page.tsx
  app/search/searchMates/page.tsx
  src/assets/icon_refresh.svg
  src/components/ui/badge.tsx
Labels: 🎨 퍼블리싱

#32 마이페이지 퍼블리싱
  app/meetiebadge/page.tsx
  app/my-ability/page.tsx
  app/mypage/page.tsx
  app/open-profile/page.tsx
  src/assets/badge_meetie-master.svg
  src/assets/badge_meetie-newbie.svg
  src/assets/badge_meetie-runner.svg
  src/assets/icon_info_vector.svg
  src/assets/icon_line.svg
  src/assets/icon_new-badge.svg
  src/assets/icon_openprofile-badge.svg
  src/assets/icon_openprofile-image.svg
  src/assets/icon_page open.svg
  src/assets/icon_people3.svg
  src/assets/icon_study-now-purple.svg
  src/assets/icon_studypeople.svg
  src/assets/info_vector.svg
  src/assets/mp_profile.svg
Labels: 🎨 퍼블리싱

#23 워크쓰루/온보딩 페이지에 캐러셀, 퍼널 추가하기
  app/on-boarding/page.tsx
  app/walk-through/page.tsx
  package.json
  pnpm-lock.yaml
  src/assets/chip_check.svg
  src/assets/on-boarding/chip_designer.svg
  src/assets/on-boarding/chip_developer.svg
  src/assets/on-boarding/chip_pm.svg
  src/assets/walk-through/walk-through-1.svg
  src/assets/walk-through/walk-through-2.svg
  src/assets/walk-through/walk-through-3.svg
  src/components/on-boarding/job-step.tsx
  src/components/on-boarding/period-step.tsx
  src/components/on-boarding/personality-step.tsx
  src/components/on-boarding/purpose-step.tsx
  src/components/ui/chip-group.tsx
  src/components/ui/chip.tsx
  src/components/walk-through/walk-through-carousel.tsx
Labels: 🎨 퍼블리싱

#38 feat: 마이페이지 밋티뱃지 추가
  app/meetiebadge/page.tsx
  app/my-ability/page.tsx
  package.json
  pnpm-lock.yaml
  src/components/ui/drawer.tsx
Labels: 🎨 퍼블리싱

#34 스터디룸/마감과제 progress bar 추가
  package.json
  pnpm-lock.yaml
  src/components/studyroom/task-deadline.tsx
Labels: 🎨 퍼블리싱

#39 스터디 개설/컴포넌트 추가 및 수정
  app/applyintro/page.tsx
  app/approval/page.tsx
  app/create/page.tsx
  app/createsec/page.tsx
  app/waiting/page.tsx
  package.json
  pnpm-lock.yaml
  src/assets/btn_check_off.svg
  src/assets/btn_check_on.svg
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/use-toast.ts
Labels: 🎨 퍼블리싱

#42 package-lock.json을 .gitignore에 추가합니다
  .gitignore
  pnpm-lock.yaml
Labels: 🐞 오류

#45 스터디룸 / 과제인증 퍼블리싱
  app/studyroom/assignment/page.tsx
  package.json
  src/assets/bg_particle-01.svg
  src/assets/bg_particle-02.svg
  src/assets/bg_particle-03.svg
  src/assets/icon_check-white.svg
  src/assets/icon_comment.svg
  src/components/studyroom/assignment-complete.tsx
  src/components/studyroom/assignment-detail.tsx
  src/components/studyroom/assignment-item.tsx
  src/components/studyroom/assignment-list.tsx
  src/components/ui/label.tsx
Labels: 🎨 퍼블리싱

#50 ERD 추가
  db.vuerd.json
Labels: ✨ 기능

#52 로딩 페이지 Carousel 수정
  app/create/page.tsx
  app/createsec/page.tsx
  app/established/page.tsx
  app/waiting/page.tsx
  env.local
  src/assets/icon_bell.svg
  src/assets/icon_trophy.svg
  src/components/ui/carousel.tsx
Labels: 🎨 퍼블리싱

#47 [FEAT] 중간 PR - Supabase 로그인 OAuth 기능 구현하기
  app/auth/callback/route.ts
  app/page.tsx
  app/walk-through/page.tsx
  bun.lockb
  middleware.ts
  package.json
  src/assets/main/login_github.svg
  src/assets/main/login_naver.svg
  src/components/walk-through/walk-through-carousel.tsx
  src/utils/supabase/client.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
Labels: ✨ 기능

#59 refactor: 프로필카드 공통 컴포넌트로 분리
  app/established/page.tsx
  src/components/common/profile-card.tsx
Labels: 🛠 개선

#69 Feat/#68 [스터디룸] 과제/일정 추가하기
  app/studyroom/calendarAdd/page.tsx
  app/studyroom/page.tsx
  package.json
  src/components/studyroom/add-assignment.tsx
  src/components/studyroom/add-meetup.tsx
  src/components/studyroom/inactive-room.tsx
  src/components/studyroom/week-month-calendar.tsx
Labels: ✨ 기능

#65 중간 PR: 컴포넌트 분리
  app/apply/[studyid]/application/page.tsx
  app/apply/[studyid]/page.tsx
  app/create-info/page.tsx
  app/create/page.tsx
  app/createsec/page.tsx
  app/established/page.tsx
  app/waiting/page.tsx
  db.vuerd.json
  src/components/studycreate/create-context.ts
  src/components/studycreate/create-drawer.tsx
  src/components/studycreate/create-first-step.tsx
  src/components/studycreate/create-progress.tsx
  src/components/studycreate/create-second-step.tsx
  src/components/studycreate/study-header.tsx
Labels: 🛠 개선

#71 feat: 스터디 생성페이지 라우팅 경로 수정 및 useFunnel 일부 적용
  app/create-info/page.tsx
  app/create/page.tsx
  src/components/studycreate/create-study-funnel.tsx
  src/components/studycreate/step-first-input.tsx
  src/components/studycreate/step-second-input.tsx
  src/components/studycreate/step-total.tsx
Labels: 🐞 오류, ✨ 기능, 🛠 개선

#75 supabase DB 연결 & 스터디 필터 적용
  app/search/page.tsx
  app/study-data/page.tsx
  package-lock.json
  package.json
  src/apis/studys-rls.ts
  src/components/searchstudy/search-header.tsx
  src/components/searchstudy/search-mate.tsx
  src/components/searchstudy/search-study.tsx
  src/components/searchstudy/study-card.tsx
  src/hooks/useStudysController.ts
  src/lib/client/supabase.ts
  src/types/supabase.ts
Labels: ✨ 기능

#77 feat: 마이페이지 기능 개발
  app/my-ability/page.tsx
  app/mypage/page.tsx
  app/open-profile/page.tsx
  src/components/my-ability/meetie-badge.tsx
Labels: 🎨 퍼블리싱, ✨ 기능

#80 스터디 탐색 리스트 & 필터링
  app/search/page.tsx
  app/study-data/page.tsx
  src/apis/studys-rls.ts
  src/assets/searchStudy/icon_exclamation-mark.svg
  src/components/searchstudy/no-result.tsx
  src/components/searchstudy/search-mate.tsx
  src/components/searchstudy/search-study.tsx
  src/components/ui/skeleton.tsx
  src/hooks/useStudysController.ts
Labels: ✨ 기능, 🛠 개선

#79 feat: 마이페이지 라우팅 경로 정리
  app/mypage/my-ability/page.tsx
  app/mypage/open-profile/page.tsx
Labels: 🛠 개선
