Repository team-swith/swith-client, pull requests merged in 2024-09, with the labels that each got.

#82 feat: 마이페이지 기능 개발(더미 데이터 확인)
  app/mypage/my-ability/page.tsx
  app/mypage/open-profile/page.tsx
  app/mypage/page.tsx
  app/open-profile/page.tsx
  src/apis/user-rls.ts
  src/hooks/useUserController.ts
Labels: 🎨 퍼블리싱, ✨ 기능, 🛠 개선

#84 스터디 생성하기 항목 데이터 베이스로 insert
  app/waiting/page.tsx
  src/components/studycreate/create-drawer.tsx
  src/components/studycreate/create-study-funnel.tsx
  src/components/studycreate/step-first-input.tsx
  src/components/studycreate/step-second-input.tsx
  src/components/studycreate/step-total.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
Labels: ✨ 기능

#86 마이페이지 로그아웃 기능 추가
  app/mypage/page.tsx
  app/search/page.tsx
  src/apis/onboarding-rls.ts
  src/apis/signout-rls.ts
  src/apis/user-rls.ts
  src/components/on-boarding/on-boarding-funnel.tsx
  src/components/searchstudy/study-card.tsx
  src/hooks/useOnboardingController.ts
Labels: ✨ 기능, 🛠 개선

#88 feat: 마이페이지 기능 개발(내 능력 현황 더미 데이터 확인)
  app/mypage/my-ability/page.tsx
  src/apis/meetiebadge-rls.ts
  src/components/my-ability/meetie-badge.tsx
  src/hooks/useMeetieBadgeController.ts
Labels: ✨ 기능

#90 온보딩 정보 DB에 전송 기능 추가
  app/auth/callback/route.ts
  app/walk-through/page.tsx
  src/apis/onboarding-rls.ts
  src/apis/signout-rls.ts
  src/apis/user-rls.ts
  src/components/on-boarding/on-boarding-funnel.tsx
  src/components/on-boarding/period-step.tsx
  src/hooks/useOnboardingController.ts
  src/hooks/useUserController.ts
Labels: ✨ 기능, 🛠 개선

#92 Feature/#85
  app/apply/[studyid]/application/page.tsx
  app/apply/[studyid]/page.tsx
  app/waiting/page.tsx
  src/components/searchstudy/search-study.tsx
  src/components/studycreate/create-drawer.tsx
  src/components/studycreate/create-study-funnel.tsx
  src/components/studycreate/step-first-input.tsx
  src/components/studycreate/step-second-input.tsx
  src/components/studycreate/step-total.tsx
Labels: ✨ 기능

#95 팀원 탐색 - 리스트, 필터 기능 추가
  next.config.mjs
  src/apis/user-rls.ts
  src/components/common/no-result.tsx
  src/components/searchstudy/mate-card.tsx
  src/components/searchstudy/search-mate.tsx
  src/components/searchstudy/search-study.tsx
  src/components/searchstudy/study-card.tsx
  src/hooks/useMatesController.ts
  src/hooks/useStudysController.ts
  src/hooks/useUserController.ts
  src/hooks/useUserDataController.ts
Labels: ✨ 기능, 🛠 개선

#97 Feat/#93
  app/apply/[studyid]/application/page.tsx
  app/apply/[studyid]/page.tsx
  src/components/studycreate/create-study-funnel.tsx
  src/components/studycreate/step-second-input.tsx
  src/components/studycreate/step-total.tsx
Labels: ✨ 기능

#100 마이페이지 기능 개발(밋티 뱃지)
  app/mypage/my-ability/page.tsx
  app/mypage/page.tsx
  app/open-profile/page.tsx
  src/assets/user.svg
  src/components/common/user-profile-img.tsx
  src/components/my-ability/meetie-badge.tsx
Labels: ✨ 기능, 🛠 개선

#101 온보딩 & 마이페이지 수정
  app/established/page.tsx
  app/layout.tsx
  app/mypage/page.tsx
  app/on-boarding/done/page.tsx
  app/open-profile/page.tsx
  next.config.mjs
  src/apis/user-rls.ts
  src/assets/on-boarding/chip_developer.svg
  src/components/common/bottom-nav-bar.tsx
  src/components/common/profile-card.tsx
  src/components/on-boarding/job-step.tsx
  src/components/on-boarding/period-step.tsx
  src/components/on-boarding/personality-step.tsx
  src/components/on-boarding/purpose-step.tsx
  src/components/searchstudy/mate-card.tsx
  src/components/searchstudy/search-mate.tsx
  src/components/searchstudy/search-study.tsx
  src/components/searchstudy/study-card.tsx
  src/components/studyroom/inactive-room.tsx
  src/components/ui/badge.tsx
  src/hooks/useOnboardingController.ts
  src/hooks/useStudysController.ts
  src/hooks/useUserController.ts
Labels: 🛠 개선

#105 마이페이지_뱃지 프로그레스바 추가
  src/components/my-ability/meetie-badge.tsx
Labels: ✨ 기능

#104 대기 중 요청 페이지 중간 PR
  app/apply/[studyid]/application/page.tsx
  app/apply/[studyid]/page.tsx
  app/waiting/[studyid]/page.tsx
  app/waiting/page.tsx
  package.json
  src/components/searchstudy/study-card.tsx
  src/components/studycreate/step-total.tsx
  src/components/ui/alert-dialog.tsx
Labels: ✨ 기능

#106 탐색 - 북마크, 친구 추가 기능 추가
  app/mypage/friends/page.tsx
  app/mypage/page.tsx
  app/open-profile/[userid]/page.tsx
  src/apis/user-rls.ts
  src/components/searchstudy/mate-card.tsx
  src/components/searchstudy/search-mate.tsx
  src/components/searchstudy/study-card.tsx
  src/hooks/useUserController.ts
Labels: ✨ 기능, 🛠 개선

#114 마이페이지 - 스터디 친구목록 수정 및 프로필 수정 버튼 추가
  app/mypage/friends/page.tsx
  app/mypage/page.tsx
  src/components/searchstudy/mate-card.tsx
  src/components/searchstudy/search-mate.tsx
  src/hooks/useUserController.ts
Labels: 🛠 개선

#119 마이페이지, 공개프로필 수정
  app/mypage/friends/page.tsx
  app/mypage/page.tsx
  app/mypage/studylist/[statusid]/page.tsx
  app/on-boarding/done/page.tsx
  app/open-profile/[userid]/page.tsx
  db.vuerd.json
  src/apis/studys-rls.ts
  src/components/searchstudy/search-mate.tsx
  src/components/searchstudy/search-study.tsx
  src/components/searchstudy/study-card.tsx
  src/hooks/useStudysController.ts
  src/hooks/useUserController.ts
Labels: 🛠 개선
